pillowtop/listener.py

oops: https://github.com/dimagi/commcare-hq/pull/5547

return value from inner function

---

pillowtop/management/commands/ptop_es_manage.py
pillowtop/management/pillowstate.py
setup.py

misc cleanup as well
codependent on https://github.com/dimagi/commcare-hq/pull/6181

rewrite get_pillow_states to use elasticsearch library

---

pillowtop/listener.py

looking at logs it seems this thing only really fires when elastic is down. proposing that we get rid of it and see if there are any bad side effects.

remove autoretry_connection

---

pillowtop/listener.py

also uses the new elasticsearch library to perform this.
(cherry picked from commit 2ff73e9970d0edc19f137b592406807db20f6f75)
Conflicts:
pillowtop/listener.py

combine two doc_exists functions, one of which was never getting called

---

pillow_retry/tasks.py

ignore unused task results

---

pillow_retry/tasks.py
setup.py

http://manage.dimagi.com/default.asp?169574
@benrudolph buddy

don't process errors if the pillow is deleted

---

pillow_retry/migrations/007_remove_like_indexes.py

remove like indexes from pillow_retry

---

settings.py

update redis package

---

settings.py

Revert "update redis package"

---

settings.py

Revert "Revert "update redis package""

---

pillow_retry/models.py
pillowtop/utils.py

Gets rid of some deprecation warnings for django 1.7

Deprecation

---

pillowtop/listener.py

Migration Pillow

---

pillowtop/listener.py

http://manage.dimagi.com/default.asp?181255
@NoahCarnahan

swap order of atomic and retry

---

README.md
pillowtop/listener.py
pillowtop/management/commands/run_ptop.py

codependent with https://github.com/dimagi/commcare-hq/pull/8163
probably easiest read commit by commit. this has no real functional changes and mostly just removes a bunch of legacy/duplicated code
@snopoke @dannyroberts cc @emord

cleanup aliased elastic pillows

---

pillowtop/listener.py
pillowtop/utils.py

some optimizations for the admin page

---

pillowtop/utils.py

refactor utility functions

---

pillowtop/utils.py

instantiate by default

---

pillow_retry/tasks.py

http://manage.dimagi.com/default.asp?181528
@TylerSheffels 
cc @czue

better handling for missing pillow classes

---

pillowtop/couchdb.py
pillowtop/listener.py

log errors that happen in processing

---

pillowtop/listener.py

@benrudolph what are your thoughts on this as a short term (pretty terrible) answer to the couchdbkit bug we just found

sleep forever when encountering any error

---

pillowtop/listener.py
pillowtop/utils.py

minor refactors/renames to better enable tests and future cleanup

---

pillow_retry/tasks.py

i believe this is causing the rabbitmq issues (can explain further later)

temporarily don't bother retrying UCR pillows

---

pillow_retry/models.py
pillow_retry/tasks.py

prevent ConfigurableIndicatorPillow from being queued

---

.gitignore
.travis.yml
manage.py
pillow_retry/migrations/0002_pillowerror_queued.py
pillow_retry/models.py
pillow_retry/tasks.py
pillow_retry/tests.py
settings.py

@czue
cc @esoergel 
Together with https://github.com/dimagi/commcare-hq/pull/8439

prevent errors from being re-queued

---

pillowtop/management/commands/ptop_reset_checkpoint.py
pillowtop/tests/test_checkpoints.py

up for grabs, cc @dannyroberts

tiny pep 8 changes

---

pillow_retry/migrations/0003_auto_20151002_0944.py

http://manage.dimagi.com/default.asp?183437
@nickpell @snopoke

migrate errors from the statuc ucr pillow rename

---

pillow_retry/migrations/0003_auto_20151002_0944.py

delete old errors that have already been retried

---

pillow_retry/migrations/0003_auto_20151002_0944.py

avoid transaction error

---

README.md
pillow_retry/tasks.py
pillowtop/__init__.py
pillowtop/listener.py
pillowtop/management/commands/ptop_es_manage.py
pillowtop/management/commands/ptop_reset_checkpoint.py
pillowtop/management/commands/ptop_run_docs.py
pillowtop/management/commands/run_ptop.py
pillowtop/run_pillowtop.py
pillowtop/tests/test_import_pillows.py
pillowtop/utils.py
setup.py

no functional changes, just some cleanup i was doing from a while back (will throw on staging for a bit)
@dannyroberts 
commit-by-commit

Changes refactor

---

.travis.yml
pillowtop/tests/__init__.py
pillowtop/tests/test_elasticsearch.py
pillowtop/tests/utils.py
settings.py
setup.py

add AliasedElasticPillow tests

---

pillowtop/tests/test_import_pillows.py
pillowtop/utils.py

http://manage.dimagi.com/default.asp?183916
@dannyroberts broke this in my refactor. ran tests locally and all's well.

add test and fix for get_pillow_by_name

---

pillowtop/listener.py

http://manage.dimagi.com/default.asp?184396
@snopoke cc @dannyroberts

fix bad function args

---

pillowtop/exceptions.py
pillowtop/feed/interface.py
pillowtop/listener.py
pillowtop/management/commands/run_ptop.py
pillowtop/pillow/interface.py
pillowtop/tests/test_elasticsearch.py
pillowtop/tests/test_import_pillows.py
pillowtop/utils.py

@snopoke @dannyroberts cc @proteusvacuum 
I believe these are all small and safe changes, though am open to push back on that given past issues. I was pretty careful testing every path of `run_ptop`
can be read commit by commit

more small pillowtop cleanup

---

pillowtop/utils.py

need to call this with other args for tests and such

split config accessor out to be passed in pillows

---

pillowtop/feed/interface.py
pillowtop/pillow/interface.py
pillowtop/processor.py
pillowtop/tests/test_import_pillows.py

small changes to underlying api/framework

---

pillowtop/listener.py
pillowtop/utils.py

codependent with https://github.com/dimagi/commcare-hq/pull/8792

update get_pillow_json to be compatible with new-style declarations

---

pillowtop/listener.py

http://manage.dimagi.com/default.asp?185283

don't process changes without IDs (and soft assert them)

---

pillowtop/listener.py

http://manage.dimagi.com/default.asp?185327
@czue what do you think of this approach?

process chunk after max wait time

---

pillowtop/listener.py
setup.py

http://manage.dimagi.com/default.asp?186039
@czue 
cc @sravfeyn

handle 404 errors

---

pillowtop/listener.py

http://manage.dimagi.com/default.asp?186218
https://www.elastic.co/guide/en/elasticsearch/reference/0.90/docs-update.html
@czue
I think these were always happening but we weren't aware of them. With the rawes upgrade it now raises Exceptions for return codes >= 400.

add retry_on_conflict param to ES requests

---

pillowtop/processor.py

related to http://manage.dimagi.com/default.asp?186282
@emord cc @calellowitz / anyone

add noop processor

---

pillowtop/admin.py
pillowtop/checkpoints/manager.py
pillowtop/dao/django.py
pillowtop/migrations/0001_initial.py
pillowtop/models.py
pillowtop/pillow/interface.py
pillowtop/tests/test_checkpoints.py
pillowtop/tests/test_import_pillows.py
settings.py

gonna throw this on staging for a bit.
@snopoke cc @calellowitz

add way to use SQL for checkpoints instead of couch

---

pillowtop/listener.py

@snopoke sorry, should have realized this would have happened

override method to prevent duplicate checkpoint updates

---

pillowtop/utils.py

http://manage.dimagi.com/default.asp?186497
up for grabs @calellowitz

use timezoneless dates everywhere

---

pillowtop/checkpoints/manager.py
pillowtop/listener.py

Sql checkpoint tweaks

---

pillowtop/listener.py

:blowfish: 
@snopoke @calellowitz

Small tweaks to pillow construction/field access

---

pillow_retry/tasks.py
pillow_retry/tests.py
pillowtop/utils.py

remove couch_db refs

---

pillowtop/listener.py
pillowtop/tests/test_import_pillows.py

Changes to facilitate regular pillows actually using a different `ChangeFeed`
:blowfish: @calellowitz @snopoke 
going to test this on staging for a bit so don't merge

Change feed override

---

pillowtop/listener.py
pillowtop/tests/test_elasticsearch.py

@snopoke :blowfish: (though some commits didn't end up in the final product)

tests and fixes for assume_alias

---

pillowtop/feed/couch.py
pillowtop/feed/interface.py
pillowtop/feed/mock.py
pillowtop/utils.py

push getting the latest change ID into the change_feed object

---

pillowtop/utils.py

fail gracefully if seq is an empty string

---

pillow_retry/tasks.py
pillow_retry/tests.py
pillowtop/utils.py

http://manage.dimagi.com/default.asp?187367
@snopoke cc @orangejenny

don't fail hard on retry when a pillow class moves/is deleted

---

pillowtop/listener.py
pillowtop/tests/test_elasticsearch.py

:blowfish: @snopoke cc @orangejenny 
mutually dependent with https://github.com/dimagi/commcare-hq/pull/9321

tweaks to allow migrating elasticsearch pillow checkpoints

---

pillow_retry/tasks.py
pillowtop/feed/interface.py
pillowtop/listener.py
pillowtop/tests/test_changes.py

:blowfish: 
@benrudolph @snopoke 
goes with https://github.com/dimagi/commcare-hq/pull/9432 and https://github.com/dimagi/fluff/pull/115

small changes to allow fluff pillows to lazily load documents

---

pillowtop/listener.py
pillowtop/tests/test_elasticsearch.py
pillowtop/tests/utils.py
settings.py

@NoahCarnahan this should provide test compatibility for 1.0.
cc @snopoke @benrudolph

Es 1.0 test fixes

---

pillowtop/es_utils.py
pillowtop/listener.py
pillowtop/management/commands/ptop_es_manage.py
pillowtop/tests/test_elasticsearch.py

should be straightforward to review either way.
@benrudolph cc @snopoke

move elasticsearch functionality out of pillows

---

pillowtop/es_utils.py
pillowtop/listener.py
pillowtop/tests/test_elasticsearch.py

pull out mapping stuff
